version: '1'

services:
    heroverse_web:
        container_name: nextjs
        image: nextjs:latest
        build:
            context: .
            target: runner
            args:
                APP_ENV: development
                BASE_URL: http://localhost:3200
                API_ENDPOINT: http://localhost:3434/api/v1
                GTM_ID:

                API_TIMEOUT: 30000
                CODE_SUCCESS: 200
                CODE_TIME_OUT: 408
                EXPIRED_TOKEN: 401
                NETWORK_ERROR: NETWORK_ERROR
                TIME_ERROR: TIMEOUT_ERROR
        environment:
            TERM: linux
            LANG: 'C.UTF-8'
            LOG_ROTATION_DAY: 7
            NODE_ENV: production
        logging:
            driver: json-file
            options:
                max-size: '50m'
                max-file: '2'
        restart: 'always'
        ports:
            - 3200:3200
